In [3]:
import numpy as np

In [4]:
vector = np.array(range(3,21))

In [5]:
vector

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [9]:
vector2 = np.array(range(0,5))

In [11]:
vector2 = np.append(vector2,vector2)

In [12]:
vector2

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [14]:
vector2.sort()

In [15]:
vector2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])